version: "3.7"

services:
  db-mysql:
    container_name: cuppa-db
    image: mysql
    environment:
      MYSQL_DATABASE: cuppa
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3307
    networks:
      - springboot-mysql-net

  application:
    container_name: cuppa-backend
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db-mysql
      - rabbitmq
    networks:
      - springboot-mysql-net

  rabbitmq:
    container_name: cuppa-mq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: cuppamq
      RABBITMQ_DEFAULT_PASS: cuppaadmin
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"

networks:
  springboot-mysql-net:
    driver: bridge