version: "3.7"

services:

  rabbitmq:
    container_name: cuppa-mq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: cuppamq
      RABBITMQ_DEFAULT_PASS: cuppaadmin
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - cuppa-net

  application:
    container_name: cuppa-backend
    build: .
    environment:
      JASPASS: ${JASPASS}
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    networks:
      - cuppa-net

networks:
  cuppa-net:
    driver: bridge