spring:
  datasource:
    url: ENC(4glFGyWM6PopeX41K2nHLg8GC/xXDklD2u5+8zLFzQCPQ8ZAH8gfjV3ZOqyKdib/y5HGcHiwyiXybyPUoLRx2fAL/Gfv/tMUUjchxS/FZkxN+cOB8d8G1FMf1w/NZDaCmzLkCu0ZkgNerG3fvtPDKfv6796UqkgvgCJTIohoEyza0RYYZBp2p26A2pbSqsOTjEsStw3fG4a+mVQ3RxPnn40FUe9ILJ92VueOXNlh5b0=)
    username: ENC(ENy8xWhahbsmkMCCnXuOzQ==)
    password: ENC(puT7Hx7MW0op8fr1TuA3Y2fVWI1kP+45)
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  rabbitmq:
    host: ENC(7YPHqbRQgeGJ1KRV3wbSGPiILEI+jnTr)
    port: 5672
    username: ENC(irStMX3WyMCfzfSDdAkIlQ==)
    password: ENC(1N6/RPClOiVEUnGRXsReTRLbwO1eb3I7)

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      cuppa:
        cuppa: debug

jasypt:
  encryptor:
    bean: encryptorBean

server:
  port: 8080