spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cuppa?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: cuppamq
    password: cuppaadmin

logging:
  level:
    com:
      cuppa:
        cuppa: debug

server:
  port: 8081