spring:
  datasource:
    url: ENC(hzpesSTLAO5EZllnW+clrAOwpd0zwLXIaOd/KKB+UcbRAb2zGW/F1CdfAgf0a+o1bSKlE/ILdYKFQY1xblfJLqqmpzMfiubsRw2OcBfPseQ7sjXwIdHtP7gYvXGRdLUU)
    username: ENC(ENy8xWhahbsmkMCCnXuOzQ==)
    password: ENC(puT7Hx7MW0op8fr1TuA3Y2fVWI1kP+45)
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  rabbitmq:
    host: ENC(7YPHqbRQgeGJ1KRV3wbSGPiILEI+jnTr)
    port: 5672
    username: ENC(irStMX3WyMCfzfSDdAkIlQ==)
    password: ENC(1N6/RPClOiVEUnGRXsReTRLbwO1eb3I7)

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      cuppa:
        cuppa: debug

jasypt:
  encryptor:
    bean: encryptorBean

server:
  port: 8080